apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: x-chkp-management=cpmanagement,x-chkp-template=cpasg,x-chkp-forwarding=HTTP-9080-3000
  labels:
    app: eureka-server
spec:
  ports:
    - port: 3000
      targetPort: 8761
  selector:
    app: eureka-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    run: eureka-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      containers:
      - name: discovery-service
        image: docker-release-local2.demo.jfrogchina.com/sample-spring-microservices/discovery-service:latest
        ports:
        - containerPort: 8761
          protocol: TCP
      imagePullSecrets:
      - name: artifactory-docker-registry

