apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
spec:
  ports:
    -
      port: 8761
      targetPort: 8761
      nodePort: 30191
  selector:
    app: discovery-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-service
  labels:
    run: discovery-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: art.local:8081/docker/discovery-service:latest
        ports:
        - containerPort: 8761
          protocol: TCP
      imagePullSecrets:
      - name: localregcred
