apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    run: gateway-server
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
    nodePort: 30555
  selector:
    run: gateway-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    run: gateway-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: art.local:8081/docker/sample-spring-microservices/gateway-service:latest
        ports:
        - containerPort: 5555
          protocol: TCP
      imagePullSecrets:
      - name: regcred-local
