apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: docker-release-local2.demo.jfrogchina.com/sample-spring-microservices/discovery-service:v1
  imagePullSecrets:
  - name: regcred
