apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.3-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: "/var/jenkins_home"
#          resources:
#            limits:
#              cpu: "1"
#              memory: 512Mi
#            requests:
#              cpu: "1"
#              memory: 512Mi
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pv-claim # must match the claim name from above
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  namespace: default
  labels:
    app: jenkins-server
spec:
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      nodePort: 31081
  selector:
    app: jenkins-server
  type: NodePort
