apiVersion: v1
kind: Service
metadata:
  name: {{ template "discovery.name" . }}
  namespace: default
  labels:
    run: {{ template "discovery.name" . }}
spec:
  ports:
    - name: port1
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    run: {{ template "discovery.name" . }}
  type: NodePort

#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ template "discovery.fullname" . }}
#  labels:
#    app: {{ template "discovery.name" . }}
#    chart: {{ template "discovery.chart" . }}
#    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - name: port1
#      port: {{ .Values.service.port }}
#      nodePort: {{ .Values.service.nodePort }}
#      protocol: TCP
#  selector:
#    app: {{ template "discovery.name" . }}
#    release: {{ .Release.Name }}
