apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    run: account-server
spec:
  ports:
    - name: port2
      protocol: TCP
      port: 2222
      nodePort: 30222
  selector:
    run: account-service
  type: NodePort
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ template "account.fullname" . }}
#  labels:
#    app: {{ template "account.name" . }}
#    chart: {{ template "account.chart" . }}
#    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: http
#      protocol: TCP
#      name: http
#  selector:
#    app: {{ template "account.name" . }}
#    release: {{ .Release.Name }}
